import type{User}from'../types';
export class ApiError extends Error{constructor(public status:number,message:string,public fields:string[]=[]){super(message)}}
const cookie=(name:string)=>decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith(name+'='))?.split('=').slice(1).join('=')??'');
async function ensureCsrf(){if(!cookie('XSRF-TOKEN'))await fetch('/login',{credentials:'include'});}
export async function api<T>(path:string,init:RequestInit={}):Promise<T>{const method=(init.method??'GET').toUpperCase();if(!['GET','HEAD','OPTIONS'].includes(method))await ensureCsrf();const headers=new Headers(init.headers);if(init.body&&!(init.body instanceof FormData)&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const token=cookie('XSRF-TOKEN');if(token)headers.set('X-XSRF-TOKEN',token);let response:Response;try{response=await fetch(path,{...init,headers,credentials:'include'});}catch{throw new ApiError(0,'Cannot reach the POS server. Check the network and try again.')}if(response.redirected&&response.url.includes('/login'))throw new ApiError(401,'Your session has expired.');if(response.status===401&&path!=='/api/pos/approvals')throw new ApiError(401,'Your session has expired.');if(!response.ok){let body:{message?:string;fields?:string[]}={};try{body=await response.json()}catch{}throw new ApiError(response.status,body.message??`Request failed (${response.status})`,body.fields)}if(response.status===204)return undefined as T;const type=response.headers.get('content-type')??'';return(type.includes('json')?response.json():response.blob())as Promise<T>}
export async function login(username:string,password:string){await ensureCsrf();const form=new URLSearchParams({username,password});const response=await fetch('/login',{method:'POST',body:form,credentials:'include',headers:{'Content-Type':'application/x-www-form-urlencoded','X-XSRF-TOKEN':cookie('XSRF-TOKEN')}});if(response.url.includes('error'))throw new ApiError(401,'Username or password is incorrect.');return currentUser()}
export async function currentUser():Promise<User>{const raw=await api<{username:string;authorities:Array<{authority?:string}|string>}>('/api/auth/me');const authority=raw.authorities.map(x=>typeof x==='string'?x:x.authority??'').find(x=>x.startsWith('ROLE_'));return{username:raw.username,role:(authority?.replace('ROLE_','')??'TELLER')as User['role']}}
export async function logout(){await api('/logout',{method:'POST'})}
export const json=(method:string,body?:unknown):RequestInit=>({method,body:body===undefined?undefined:JSON.stringify(body)});
