package com.chahinaz.pos.reporting;
import static com.chahinaz.pos.reporting.ReportingDtos.*;
import java.math.*;import java.sql.Timestamp;import java.time.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.web.server.ResponseStatusException;
@Service public class ReportingService {
 private final JdbcTemplate db;private final ZoneId zone;
 public ReportingService(JdbcTemplate db,@Value("${pos.store-timezone:Asia/Beirut}")String timezone){this.db=db;try{zone=ZoneId.of(timezone);}catch(DateTimeException e){throw new IllegalArgumentException("Invalid pos.store-timezone: "+timezone,e);}}
 public ReportRange range(java.time.LocalDate from,java.time.LocalDate to){return ReportRange.of(from,to,zone);} private Object[] a(ReportRange r){return new Object[]{Timestamp.from(r.start()),Timestamp.from(r.end())};} private static BigDecimal bd(Map<String,Object>m,String k){Object v=m.get(k);return v==null?BigDecimal.ZERO:new BigDecimal(v.toString());}private static long lng(Map<String,Object>m,String k){Object v=m.get(k);return v==null?0:((Number)v).longValue();}private static BigDecimal pct(BigDecimal n,BigDecimal d){return d.signum()==0?null:n.multiply(BigDecimal.valueOf(100)).divide(d,2,RoundingMode.HALF_UP);} 
 public Dashboard dashboard(ReportRange r){Map<String,Object>s=db.queryForMap("""
  select coalesce(sum(s.subtotal_usd),0) gross,coalesce(sum(s.total_usd),0) net,count(*) tx,
  coalesce(sum((select coalesce(sum(si.quantity),0) from sale_item si where si.sale_id=s.id)),0) units,
  coalesce(sum(s.total_discount_usd),0) discounts,
  coalesce(sum((select coalesce(sum(si.cost_price_usd_snapshot*si.quantity),0) from sale_item si where si.sale_id=s.id)),0) cogs
  from sale s where s.status='COMPLETED' and s.completed_at>=? and s.completed_at<?
  """,a(r));Map<String,Object>ret=db.queryForMap("""
select count(*) returns,coalesce(sum(case when sr.refund_method='LBP_CASH' then sr.refund_lbp/s.exchange_rate else sr.refund_usd end),0) refunds,coalesce(sum((select sum(si.cost_price_usd_snapshot*sri.quantity) from sale_return_item sri join sale_item si on si.id=sri.sale_item_id where sri.return_id=sr.id)),0) returned_cost from sale_return sr join sale s on s.id=sr.original_sale_id where sr.created_at>=? and sr.created_at<?""",a(r));Map<String,Object>pay=db.queryForMap("""
select coalesce(sum(case when p.payment_type='USD_CASH' then p.amount_usd else 0 end),0) usd,coalesce(sum(case when p.payment_type='LBP_CASH' then p.amount_lbp else 0 end),0) lbp,coalesce(sum(case when p.payment_type='WHISH_MANUAL' then p.amount_usd else 0 end),0) whish from payment p join sale s on s.id=p.sale_id where s.status='COMPLETED' and s.completed_at>=? and s.completed_at<?""",a(r));BigDecimal net=bd(s,"net"),refunds=bd(ret,"refunds"),netAfter=net.subtract(refunds),netCogs=bd(s,"cogs").subtract(bd(ret,"returned_cost")),profit=netAfter.subtract(netCogs);long tx=lng(s,"tx");long voids=db.queryForObject("select count(*) from sale where status='VOIDED' and voided_at>=? and voided_at<?",Long.class,a(r));long held=db.queryForObject("select count(*) from sale where status='HELD'",Long.class);long low=db.queryForObject("select count(*) from product where active and stock_quantity>0 and stock_quantity<=low_stock_threshold",Long.class);long out=db.queryForObject("select count(*) from product where active and stock_quantity=0",Long.class);ReportRange prev=previous(r);BigDecimal prevNet=netRevenue(prev);Comparison comparison=new Comparison(netAfter,prevNet,netAfter.subtract(prevNet),pct(netAfter.subtract(prevNet),prevNet));return new Dashboard(r.view(),bd(s,"gross"),net,tx,tx==0?BigDecimal.ZERO:net.divide(BigDecimal.valueOf(tx),2,RoundingMode.HALF_UP),lng(s,"units"),bd(s,"discounts"),refunds,netAfter,netCogs,profit,pct(profit,netAfter),bd(pay,"usd"),bd(pay,"lbp"),bd(pay,"whish"),lng(ret,"returns"),voids,held,low,out,comparison);}
 private ReportRange previous(ReportRange r){long days=java.time.temporal.ChronoUnit.DAYS.between(r.from(),r.to())+1;LocalDate end=r.from().minusDays(1),start=end.minusDays(days-1);return ReportRange.of(start,end,r.zone());}private BigDecimal netRevenue(ReportRange r){BigDecimal sales=db.queryForObject("select coalesce(sum(total_usd),0) from sale where status='COMPLETED' and completed_at>=? and completed_at<?",BigDecimal.class,a(r));BigDecimal refunds=db.queryForObject("select coalesce(sum(case when sr.refund_method='LBP_CASH' then sr.refund_lbp/s.exchange_rate else sr.refund_usd end),0) from sale_return sr join sale s on s.id=sr.original_sale_id where sr.created_at>=? and sr.created_at<?",BigDecimal.class,a(r));return sales.subtract(refunds);}
 public List<SalesPeriod> sales(ReportRange r,String grouping){String unit=switch(grouping==null?"daily":grouping){case"hourly"->"hour";case"daily"->"day";case"weekly"->"week";case"monthly"->"month";default->throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"grouping must be hourly, daily, weekly, or monthly");};String sql="""
with base as(select s.*,date_trunc('%s',s.completed_at at time zone '%s') bucket from sale s where s.status='COMPLETED' and s.completed_at>=? and s.completed_at<?), sold as(select sale_id,sum(quantity) units,sum(cost_price_usd_snapshot*quantity) cogs from sale_item group by sale_id), refunds as(select date_trunc('%s',sr.created_at at time zone '%s') bucket,sum(case when sr.refund_method='LBP_CASH' then sr.refund_lbp/s.exchange_rate else sr.refund_usd end) amount,sum(si.cost_price_usd_snapshot*sri.quantity) returned_cost from sale_return sr join sale s on s.id=sr.original_sale_id join sale_return_item sri on sri.return_id=sr.id join sale_item si on si.id=sri.sale_item_id where sr.created_at>=? and sr.created_at<? group by 1), agg as(select b.bucket,count(*) sales_count,coalesce(sum(x.units),0) units,sum(b.subtotal_usd) gross,sum(b.total_discount_usd) discounts,sum(b.total_usd) net,sum(x.cogs) cogs from base b join sold x on x.sale_id=b.id group by b.bucket) select a.bucket,a.sales_count,a.units,a.gross,a.discounts,coalesce(r.amount,0) refunds,a.net-coalesce(r.amount,0) net_sales,a.net/a.sales_count average,(a.net-coalesce(r.amount,0))-(a.cogs-coalesce(r.returned_cost,0)) profit from agg a left join refunds r on r.bucket=a.bucket order by a.bucket""".formatted(unit,zone.getId().replace("'","''"),unit,zone.getId().replace("'","''"));Object[] p={Timestamp.from(r.start()),Timestamp.from(r.end()),Timestamp.from(r.start()),Timestamp.from(r.end())};return db.query(sql,(rs,n)->new SalesPeriod(rs.getTimestamp(1).toLocalDateTime().toString(),rs.getLong(2),rs.getLong(3),rs.getBigDecimal(4),rs.getBigDecimal(5),rs.getBigDecimal(6),rs.getBigDecimal(7),rs.getBigDecimal(8),rs.getBigDecimal(9)),p);}
 public List<ProductPerformance> products(ReportRange r,String sort){String order=switch(sort==null?"revenue":sort){case"units"->"units_sold desc";case"revenue"->"net_revenue desc";case"profit"->"profit desc";case"lowest"->"units_sold asc";default->throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Unsupported product sort");};String sql="""
with sold as(select si.product_id,max(si.sku_snapshot) sku,max(si.product_name_snapshot) name,sum(si.quantity) units,sum(si.effective_unit_price_usd*si.quantity) gross,sum(si.discount_usd) discounts,sum(si.line_total_usd) net,sum(si.cost_price_usd_snapshot*si.quantity) cogs from sale_item si join sale s on s.id=si.sale_id where s.status='COMPLETED' and s.completed_at>=? and s.completed_at<? group by si.product_id), ret as(select si.product_id,sum(sri.quantity) qty,sum(sri.amount_usd) amount,sum(si.cost_price_usd_snapshot*sri.quantity) returned_cost from sale_return_item sri join sale_return sr on sr.id=sri.return_id join sale_item si on si.id=sri.sale_item_id where sr.created_at>=? and sr.created_at<? group by si.product_id) select p.id,coalesce(x.sku,p.sku),coalesce(x.name,p.name),coalesce(x.units,0) units_sold,coalesce(x.gross,0) gross,coalesce(x.discounts,0) discounts,coalesce(x.net,0)-coalesce(r.amount,0) net_revenue,coalesce(r.qty,0),coalesce(r.amount,0),coalesce(x.cogs,0)-coalesce(r.returned_cost,0) cogs,(coalesce(x.net,0)-coalesce(r.amount,0))-(coalesce(x.cogs,0)-coalesce(r.returned_cost,0)) profit,p.stock_quantity from product p left join sold x on x.product_id=p.id left join ret r on r.product_id=p.id order by %s,p.sku""".formatted(order);Object[]p={Timestamp.from(r.start()),Timestamp.from(r.end()),Timestamp.from(r.start()),Timestamp.from(r.end())};return db.query(sql,(rs,n)->{BigDecimal net=rs.getBigDecimal(7),profit=rs.getBigDecimal(11);return new ProductPerformance(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getLong(4),rs.getBigDecimal(5),rs.getBigDecimal(6),net,rs.getLong(8),rs.getBigDecimal(9),rs.getBigDecimal(10),profit,pct(profit,net),rs.getInt(12));},p);}
 public List<CategoryPerformance> categories(ReportRange r){String sql="""
with x as(select si.category_id_snapshot id,max(si.category_name_snapshot) name,sum(si.quantity) units,sum(si.effective_unit_price_usd*si.quantity) gross,sum(si.line_total_usd) net,sum(si.cost_price_usd_snapshot*si.quantity) cogs from sale_item si join sale s on s.id=si.sale_id where s.status='COMPLETED' and s.completed_at>=? and s.completed_at<? group by si.category_id_snapshot),ret as(select si.category_id_snapshot id,sum(sri.amount_usd) refunds,sum(si.cost_price_usd_snapshot*sri.quantity) returned_cost from sale_return_item sri join sale_return sr on sr.id=sri.return_id join sale_item si on si.id=sri.sale_item_id where sr.created_at>=? and sr.created_at<? group by si.category_id_snapshot),t as(select sum(net-coalesce(refunds,0)) total from x left join ret using(id))select x.id,x.name,x.units,x.gross,x.net-coalesce(r.refunds,0),coalesce(r.refunds,0),(x.net-coalesce(r.refunds,0))-(x.cogs-coalesce(r.returned_cost,0)),t.total from x left join ret r using(id) cross join t order by 5 desc""";Object[]p={Timestamp.from(r.start()),Timestamp.from(r.end()),Timestamp.from(r.start()),Timestamp.from(r.end())};return db.query(sql,(rs,n)->new CategoryPerformance(rs.getObject(1,UUID.class),rs.getString(2),rs.getLong(3),rs.getBigDecimal(4),rs.getBigDecimal(5),rs.getBigDecimal(6),rs.getBigDecimal(7),pct(rs.getBigDecimal(5),rs.getBigDecimal(8))),p);}
 public List<InventoryRow> inventory(ReportRange r,String stockStatus,UUID category,Boolean active){StringBuilder q=new StringBuilder("""
select p.id,p.sku,p.name,c.name,p.stock_quantity,p.low_stock_threshold,case when p.stock_quantity=0 then 'OUT_OF_STOCK' when p.stock_quantity<=p.low_stock_threshold then 'LOW_STOCK' when p.stock_quantity<=p.low_stock_threshold+2 then 'APPROACHING' else 'IN_STOCK' end status,p.active,p.cost_price_usd,p.cost_price_usd*p.stock_quantity,coalesce(sum(case when s.status='COMPLETED' and s.completed_at>=? and s.completed_at<? then si.quantity else 0 end),0) sold,coalesce((select sum(im.quantity_change) from inventory_movement im where im.product_id=p.id and im.movement_type='RETURN' and im.occurred_at>=? and im.occurred_at<?),0) restocked,coalesce((select sum(sri.quantity) from sale_return_item sri join sale_return sr on sr.id=sri.return_id join sale_item x on x.id=sri.sale_item_id where x.product_id=p.id and not sri.restockable and sr.created_at>=? and sr.created_at<?),0) nonrestock from product p join category c on c.id=p.category_id left join sale_item si on si.product_id=p.id left join sale s on s.id=si.sale_id where 1=1""");List<Object>p=new ArrayList<>(List.of(Timestamp.from(r.start()),Timestamp.from(r.end()),Timestamp.from(r.start()),Timestamp.from(r.end()),Timestamp.from(r.start()),Timestamp.from(r.end())));if(category!=null){q.append(" and p.category_id=?");p.add(category);}if(active!=null){q.append(" and p.active=?");p.add(active);}if(stockStatus!=null){switch(stockStatus){case"out"->q.append(" and p.stock_quantity=0");case"low"->q.append(" and p.stock_quantity>0 and p.stock_quantity<=p.low_stock_threshold");case"approaching"->q.append(" and p.stock_quantity>p.low_stock_threshold and p.stock_quantity<=p.low_stock_threshold+2");case"in"->q.append(" and p.stock_quantity>p.low_stock_threshold+2");default->throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid stock status");}}q.append(" group by p.id,c.name order by p.name");return db.query(q.toString(),(rs,n)->new InventoryRow(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getInt(6),rs.getString(7),rs.getBoolean(8),rs.getBigDecimal(9),rs.getBigDecimal(10),rs.getLong(11),rs.getLong(12),rs.getLong(13)),p.toArray());}
 public PaymentSummary payments(ReportRange r){Map<String,Object>m=db.queryForMap("""
select coalesce(sum(amount_paid_usd),0) usd,coalesce(sum(amount_paid_lbp),0) lbp,coalesce(sum(whish_amount_usd),0) whish,count(*) filter(where amount_paid_usd>0 and amount_paid_lbp=0 and whish_amount_usd=0) usd_only,count(*) filter(where amount_paid_lbp>0 and amount_paid_usd=0 and whish_amount_usd=0) lbp_only,count(*) filter(where whish_amount_usd>0 and amount_paid_usd=0 and amount_paid_lbp=0) whish_only,count(*) filter(where (case when amount_paid_usd>0 then 1 else 0 end)+(case when amount_paid_lbp>0 then 1 else 0 end)+(case when whish_amount_usd>0 then 1 else 0 end)>1) mixed from sale where status='COMPLETED' and completed_at>=? and completed_at<?""",a(r));return new PaymentSummary(bd(m,"usd"),bd(m,"lbp"),bd(m,"whish"),lng(m,"usd_only"),lng(m,"lbp_only"),lng(m,"whish_only"),lng(m,"mixed"));}
 public List<RegisterReport> registers(ReportRange r){return db.query("""
select r.id,e.id,e.display_name,r.opened_at,r.closed_at,r.status,r.opening_cash_usd,r.opening_cash_lbp,r.expected_closing_cash_usd,r.expected_closing_cash_lbp,r.actual_closing_cash_usd,r.actual_closing_cash_lbp,r.difference_usd,r.difference_lbp,count(distinct s.id),coalesce(sum(s.amount_paid_usd-s.change_usd),0),coalesce(sum(s.amount_paid_lbp-s.change_lbp),0),coalesce((select sum(sr.refund_usd) from sale_return sr where sr.register_session_id=r.id),0),coalesce((select sum(sr.refund_lbp) from sale_return sr where sr.register_session_id=r.id),0) from register_session r join employee e on e.id=r.employee_id left join sale s on s.register_session_id=r.id and s.status='COMPLETED' where r.opened_at>=? and r.opened_at<? group by r.id,e.id,e.display_name order by r.opened_at desc""",(rs,n)->new RegisterReport(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getString(3),rs.getTimestamp(4).toInstant(),rs.getTimestamp(5)==null?null:rs.getTimestamp(5).toInstant(),rs.getString(6),rs.getBigDecimal(7),rs.getBigDecimal(8),rs.getBigDecimal(9),rs.getBigDecimal(10),rs.getBigDecimal(11),rs.getBigDecimal(12),rs.getBigDecimal(13),rs.getBigDecimal(14),rs.getLong(15),rs.getBigDecimal(16),rs.getBigDecimal(17),rs.getBigDecimal(18),rs.getBigDecimal(19)),a(r));}
 public List<ReturnReport> returns(ReportRange r){return db.query("""
select sr.id,s.sale_number,si.sku_snapshot,si.product_name_snapshot,sri.quantity,sri.amount_usd,sri.restockable,e.display_name,sr.reason,sr.created_at from sale_return sr join sale s on s.id=sr.original_sale_id join employee e on e.id=sr.employee_id join sale_return_item sri on sri.return_id=sr.id join sale_item si on si.id=sri.sale_item_id where sr.created_at>=? and sr.created_at<? order by sr.created_at desc""",(rs,n)->new ReturnReport(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getBigDecimal(6),rs.getBoolean(7),rs.getString(8),rs.getString(9),rs.getTimestamp(10).toInstant()),a(r));}
 public List<DiscountReport> discounts(ReportRange r){return db.query("""
select s.sale_number,si.sku_snapshot,si.product_name_snapshot,si.discount_usd,case when si.effective_unit_price_usd*si.quantity=0 then null else si.discount_usd*100/(si.effective_unit_price_usd*si.quantity) end,s.cashier_name_snapshot,null,s.completed_at from sale_item si join sale s on s.id=si.sale_id where s.status='COMPLETED' and si.discount_usd>0 and s.completed_at>=? and s.completed_at<? order by s.completed_at desc""",(rs,n)->new DiscountReport(rs.getString(1),rs.getString(2),rs.getString(3),rs.getBigDecimal(4),rs.getBigDecimal(5),rs.getString(6),(UUID)rs.getObject(7),rs.getTimestamp(8).toInstant()),a(r));}
 public List<OverrideReport> overrides(ReportRange r){return db.query("""
select s.sale_number,si.sku_snapshot,si.product_name_snapshot,si.original_unit_price_usd,si.effective_unit_price_usd,si.effective_unit_price_usd-si.original_unit_price_usd,req.display_name,app.display_name,si.override_reason,si.override_at from sale_item si join sale s on s.id=si.sale_id left join employee req on req.id=si.override_requested_by left join employee app on app.id=si.override_approved_by where si.override_at>=? and si.override_at<? order by si.override_at desc""",(rs,n)->new OverrideReport(rs.getString(1),rs.getString(2),rs.getString(3),rs.getBigDecimal(4),rs.getBigDecimal(5),rs.getBigDecimal(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getTimestamp(10).toInstant()),a(r));}
 public List<VoidReport> voids(ReportRange r){return db.query("select s.sale_number,e.display_name,s.void_reason,s.voided_at from sale s left join employee e on e.id=s.voided_by where s.status='VOIDED' and s.voided_at>=? and s.voided_at<? order by s.voided_at desc",(rs,n)->new VoidReport(rs.getString(1),rs.getString(2),rs.getString(3),rs.getTimestamp(4).toInstant()),a(r));}
 public PageResponse<MovementReport> movements(ReportRange r,int page,int size){if(page<0||size<1||size>100)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"page must be nonnegative and size must be 1 through 100");long total=db.queryForObject("select count(*) from inventory_movement where occurred_at>=? and occurred_at<?",Long.class,a(r));List<MovementReport> content=db.query("select im.id,p.sku,p.name,im.movement_type,im.quantity_change,im.resulting_quantity,im.reason,im.sale_id,im.return_id,im.occurred_at from inventory_movement im join product p on p.id=im.product_id where im.occurred_at>=? and im.occurred_at<? order by im.occurred_at desc limit ? offset ?",(rs,n)->new MovementReport(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getInt(6),rs.getString(7),rs.getObject(8,UUID.class),rs.getObject(9,UUID.class),rs.getTimestamp(10).toInstant()),Timestamp.from(r.start()),Timestamp.from(r.end()),size,(long)page*size);return new PageResponse<>(content,page,size,total,(int)((total+size-1)/size));}
}


