package com.chahinaz.pos.reporting;
import static com.chahinaz.pos.reporting.ReportingDtos.*;import java.time.LocalDate;import java.util.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/management/reports") public class ReportingController {private final ReportingService reports;private final ExcelExportService excel;public ReportingController(ReportingService r,ExcelExportService e){reports=r;excel=e;}private ReportRange range(LocalDate f,LocalDate t){return reports.range(f,t);}
 @GetMapping("/dashboard")public Dashboard dashboard(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return reports.dashboard(range(from,to));}
 @GetMapping("/sales")public List<SalesPeriod> sales(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(defaultValue="daily")String grouping){return reports.sales(range(from,to),grouping);}
 @GetMapping("/products")public List<ProductPerformance> products(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(defaultValue="revenue")String sort){return reports.products(range(from,to),sort);}
 @GetMapping("/categories")public List<CategoryPerformance> categories(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return reports.categories(range(from,to));}
 @GetMapping("/inventory")public List<InventoryRow> inventory(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(required=false)String stockStatus,@RequestParam(required=false)UUID categoryId,@RequestParam(required=false)Boolean active){return reports.inventory(range(from,to),stockStatus,categoryId,active);}
 @GetMapping("/payments")public PaymentSummary payments(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return reports.payments(range(from,to));}
 @GetMapping("/registers")public List<RegisterReport> registers(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return reports.registers(range(from,to));}
 @GetMapping("/returns")public List<ReturnReport> returns(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return reports.returns(range(from,to));}
 @GetMapping("/discounts")public List<DiscountReport> discounts(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return reports.discounts(range(from,to));}
 @GetMapping("/price-overrides")public List<OverrideReport> overrides(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return reports.overrides(range(from,to));}
 @GetMapping("/voids")public List<VoidReport> voids(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return reports.voids(range(from,to));}
 @GetMapping("/inventory-movements")public PageResponse<MovementReport> movements(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="25")int size){return reports.movements(range(from,to),page,size);}
 @GetMapping(value="/exports/{type}",produces="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")public ResponseEntity<byte[]> export(@PathVariable String type,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){ReportRange r=range(from,to);return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\"chahinaz-"+type+"-"+r.from()+"-"+r.to()+".xlsx\"").body(excel.export(type,r,reports));}
}
