import{cleanup,render,screen,waitFor}from'@testing-library/react';import userEvent from'@testing-library/user-event';import{afterEach,describe,expect,it,vi}from'vitest';import{App}from'./App';
afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe('POS shell',()=>{it('shows login when there is no session',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('',{status:401}));render(<App/>);expect(await screen.findByRole('heading',{name:'Store POS'})).toBeVisible();expect(screen.getByLabelText('Username')).toBeVisible()});it('shows role-aware teller navigation',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const url=String(input);if(url.includes('/api/auth/me'))return Response.json({username:'maya',authorities:[{authority:'ROLE_TELLER'}]});if(url.includes('/api/pos/registers/current'))return new Response(JSON.stringify({message:'No register'}),{status:404,headers:{'Content-Type':'application/json'}});if(url.includes('/api/pos/products')||url.includes('/api/pos/categories'))return Response.json([]);return Response.json([])});render(<App/>);expect(await screen.findByText('maya')).toBeVisible();expect(screen.getByRole('link',{name:'SELL'})).toBeVisible();expect(screen.queryByRole('link',{name:'REPORTS'})).not.toBeInTheDocument();expect(screen.queryByRole('link',{name:'ADMIN'})).not.toBeInTheDocument()});it('filters products from cashier search',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const url=String(input);if(url.includes('/api/auth/me'))return Response.json({username:'owner',authorities:[{authority:'ROLE_ADMIN'}]});if(url.includes('/api/pos/registers/current'))return new Response('{}',{status:404,headers:{'Content-Type':'application/json'}});if(url.includes('/api/pos/categories'))return Response.json([{id:'c',name:'Home',active:true}]);if(url.includes('/api/pos/products'))return Response.json([{id:'1',sku:'MUG-1',name:'Orange Mug',categoryId:'c',categoryName:'Home',sellingPriceUsd:1,inStock:true},{id:'2',sku:'BAG-1',name:'Blue Bag',categoryId:'c',categoryName:'Home',sellingPriceUsd:1,inStock:true}]);return Response.json([])});render(<App/>);const search=await screen.findByLabelText('Search products');await userEvent.type(search,'mug');await waitFor(()=>expect(screen.getByText('Orange Mug')).toBeVisible());expect(screen.queryByText('Blue Bag')).not.toBeInTheDocument()})});

describe('cashier behavior',()=>{
 it('shows manager and admin navigation according to role',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const u=String(input);if(u.includes('/api/auth/me'))return Response.json({username:'manager',authorities:['ROLE_MANAGER']});if(u.includes('/registers/current'))return new Response('{}',{status:404});return Response.json([])});render(<App/>);expect(await screen.findByRole('link',{name:'REPORTS'})).toBeVisible();expect(screen.queryByRole('link',{name:'ADMIN'})).not.toBeInTheDocument()});
 it('reports invalid authentication',async()=>{document.cookie='XSRF-TOKEN=test; path=/';vi.spyOn(globalThis,'fetch').mockImplementation(async(input)=>String(input).includes('/api/auth/me')?new Response('',{status:401}):new Response('',{status:302,headers:{Location:'/login?error'}}));render(<App/>);await userEvent.type(await screen.findByLabelText('Username'),'bad');await userEvent.type(screen.getByLabelText('Password'),'bad');await userEvent.click(screen.getByRole('button',{name:'Sign in'}));expect(await screen.findByRole('alert')).toHaveTextContent(/incorrect|expired/)});
 it('shows a backend unavailable message during sign in',async()=>{document.cookie='XSRF-TOKEN=test; path=/';let first=true;vi.spyOn(globalThis,'fetch').mockImplementation(async()=>{if(first){first=false;return new Response('',{status:401})}throw new TypeError('offline')});render(<App/>);await userEvent.type(await screen.findByLabelText('Username'),'maya');await userEvent.type(screen.getByLabelText('Password'),'password');await userEvent.click(screen.getByRole('button',{name:'Sign in'}));expect(await screen.findByRole('alert')).toBeVisible()});
 it('adds a product, changes quantity, and removes it',async()=>{document.cookie='XSRF-TOKEN=test; path=/';let current:any={id:'s1',saleNumber:'S1',status:'OPEN',createdAt:new Date().toISOString(),cashier:'Maya',items:[],subtotalUsd:0,totalDiscountUsd:0,totalUsd:0,payments:[],changeUsd:0,changeLbp:0,returns:[]};const product={id:'p1',sku:'P1',name:'Mug',categoryId:'c',categoryName:'Home',sellingPriceUsd:1,inStock:true};vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const u=String(input);if(u.includes('/auth/me'))return Response.json({username:'maya',authorities:['ROLE_TELLER']});if(u.includes('/registers/current'))return new Response('{}',{status:404});if(u.endsWith('/products'))return Response.json([product]);if(u.endsWith('/categories'))return Response.json([]);if(u.endsWith('/sales')&&init?.method==='POST')return Response.json(current,{status:201});if(u.includes('/items')){if(init?.method==='DELETE')current={...current,items:[],subtotalUsd:0,totalUsd:0};else{const q=init?.method==='PUT'?Number(JSON.parse(String(init.body)).quantity):1;current={...current,items:[{id:'i1',productId:'p1',sku:'P1',name:'Mug',originalUnitPriceUsd:1,unitPriceUsd:1,discountUsd:0,quantity:q,lineTotalUsd:q}],subtotalUsd:q,totalUsd:q}}return Response.json(current)}return Response.json([])});render(<App/>);await userEvent.click(await screen.findByRole('button',{name:/Mug/}));expect(await screen.findByText('1')).toBeVisible();await userEvent.click(screen.getByLabelText('Increase Mug'));expect(await screen.findByText('2')).toBeVisible();await userEvent.click(screen.getByLabelText('Decrease Mug'));await userEvent.click(screen.getByLabelText('Decrease Mug'));expect(await screen.findByText('Cart is empty')).toBeVisible()});
});

describe('catalogue and held sales',()=>{
 it('filters the catalogue by category',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const u=String(input);if(u.includes('/auth/me'))return Response.json({username:'maya',authorities:['ROLE_TELLER']});if(u.includes('/registers/current'))return new Response('{}',{status:404});if(u.endsWith('/categories'))return Response.json([{id:'home',name:'Home',active:true},{id:'party',name:'Party',active:true}]);if(u.endsWith('/products'))return Response.json([{id:'p1',sku:'P1',name:'Mug',categoryId:'home',categoryName:'Home',sellingPriceUsd:1,inStock:true},{id:'p2',sku:'P2',name:'Balloons',categoryId:'party',categoryName:'Party',sellingPriceUsd:1,inStock:true}]);return Response.json([])});render(<App/>);await userEvent.click(await screen.findByRole('button',{name:'Party'}));expect(screen.getByText('Balloons')).toBeVisible();expect(screen.queryByText('Mug')).not.toBeInTheDocument()});
 it('holds and resumes the current sale',async()=>{document.cookie='XSRF-TOKEN=test; path=/';const item={id:'i1',productId:'p1',sku:'P1',name:'Mug',originalUnitPriceUsd:1,unitPriceUsd:1,discountUsd:0,quantity:1,lineTotalUsd:1};const empty={id:'s1',saleNumber:'S1',status:'OPEN',createdAt:new Date().toISOString(),cashier:'Maya',items:[],subtotalUsd:0,totalDiscountUsd:0,totalUsd:0,payments:[],changeUsd:0,changeLbp:0,returns:[]};const held={...empty,status:'HELD',items:[item],subtotalUsd:1,totalUsd:1};vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const u=String(input);if(u.includes('/auth/me'))return Response.json({username:'maya',authorities:['ROLE_TELLER']});if(u.includes('/registers/current'))return new Response('{}',{status:404});if(u.endsWith('/products'))return Response.json([{id:'p1',sku:'P1',name:'Mug',categoryId:'c',categoryName:'Home',sellingPriceUsd:1,inStock:true}]);if(u.endsWith('/categories'))return Response.json([]);if(u.endsWith('/sales')&&init?.method==='POST')return Response.json(empty,{status:201});if(u.endsWith('/items'))return Response.json({...held,status:'OPEN'});if(u.endsWith('/hold'))return Response.json(held);if(u.endsWith('/held'))return Response.json([held]);if(u.endsWith('/resume'))return Response.json({...held,status:'OPEN'});return Response.json([])});render(<App/>);await userEvent.click(await screen.findByRole('button',{name:/Mug/}));await userEvent.click(await screen.findByRole('button',{name:'Hold sale'}));const resume=await screen.findByRole('button',{name:/S1 · 1 items/});await userEvent.click(resume);expect((await screen.findAllByText('Mug')).length).toBeGreaterThan(1)});
});

