import{cleanup,render,screen,waitFor}from'@testing-library/react';import userEvent from'@testing-library/user-event';import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{Checkout,CloseRegister,OpenRegister}from'./App';import type{Register,Sale}from'./types';
const sale:Sale={id:'s1',saleNumber:'S1',status:'OPEN',createdAt:'2026-09-21T10:00:00Z',cashier:'Maya',items:[{id:'i1',productId:'p1',sku:'P1',name:'Mug',originalUnitPriceUsd:3,unitPriceUsd:3,discountUsd:0,quantity:1,lineTotalUsd:3}],subtotalUsd:3,totalDiscountUsd:0,totalUsd:3,payments:[],changeUsd:0,changeLbp:0,returns:[]};
const register:Register={id:'r1',employeeName:'Maya',status:'OPEN',openedAt:'2026-09-21T09:00:00Z',openingCashUsd:10,openingCashLbp:100000};
beforeEach(()=>{document.cookie='XSRF-TOKEN=test; path=/'});afterEach(()=>{cleanup();vi.restoreAllMocks()});
async function checkout(fields:{usd?:string;lbp?:string;whish?:string;confirm?:boolean}){const fetch=vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json({...sale,status:'COMPLETED'}));render(<Checkout sale={sale} register={register} onRegister={()=>{}} onClose={()=>{}} onComplete={()=>{}}/>);if(fields.usd)await userEvent.type(screen.getByLabelText('USD cash received'),fields.usd);if(fields.lbp)await userEvent.type(screen.getByLabelText('LBP cash received'),fields.lbp);if(fields.whish)await userEvent.type(screen.getByLabelText('Whish amount'),fields.whish);if(fields.confirm)await userEvent.click(screen.getByText('Whish manually confirmed'));await userEvent.click(screen.getByRole('button',{name:'Complete sale'}));await waitFor(()=>expect(fetch).toHaveBeenCalled());return JSON.parse(String(fetch.mock.calls[0][1]?.body));}
describe('checkout and register forms',()=>{
 it('submits USD cash exactly',async()=>expect(await checkout({usd:'3'})).toMatchObject({paidUsd:3,paidLbp:0,whishUsd:0}));
 it('submits LBP cash exactly',async()=>expect(await checkout({lbp:'268500'})).toMatchObject({paidUsd:0,paidLbp:268500,whishUsd:0}));
 it('submits mixed USD and LBP without client-side conversion',async()=>expect(await checkout({usd:'1',lbp:'179000'})).toMatchObject({paidUsd:1,paidLbp:179000}));
 it('submits Whish only when manually confirmed',async()=>expect(await checkout({whish:'3',confirm:true})).toMatchObject({whishUsd:3,whishManuallyConfirmed:true}));
 it('opens a register with both currencies',async()=>{const fetch=vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json(register,{status:201}));render(<OpenRegister onDone={()=>{}}/>);await userEvent.clear(screen.getByLabelText('Opening USD'));await userEvent.type(screen.getByLabelText('Opening USD'),'25');await userEvent.clear(screen.getByLabelText('Opening LBP'));await userEvent.type(screen.getByLabelText('Opening LBP'),'500000');await userEvent.click(screen.getByRole('button',{name:'Open and continue'}));await waitFor(()=>expect(String(fetch.mock.calls[0][1]?.body)).toContain('500000'))});
 it('closes a register with actual drawer amounts',async()=>{const fetch=vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json({...register,status:'CLOSED'}));render(<CloseRegister current={register} done={()=>{}} cancel={()=>{}}/>);await userEvent.type(screen.getByLabelText('Actual USD'),'24');await userEvent.type(screen.getByLabelText('Actual LBP'),'490000');await userEvent.click(screen.getByRole('button',{name:'Close and calculate difference'}));await waitFor(()=>expect(String(fetch.mock.calls[0][0])).toContain('/close'))});
});
