import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react';import userEvent from'@testing-library/user-event';import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{AdvancedAdmin,AdvancedInventory,AdvancedReports,AdvancedSales,ApprovalDialog,SaleActionDialog}from'./workflows';import type{Sale}from'./types';
const sale:Sale={id:'sale-1',saleNumber:'S-1',status:'COMPLETED',createdAt:'2026-09-21T10:00:00Z',cashier:'Maya',subtotalUsd:2,totalDiscountUsd:0,totalUsd:2,items:[{id:'item-1',productId:'p1',sku:'P1',name:'Mug',originalUnitPriceUsd:1,unitPriceUsd:1,discountUsd:0,quantity:2,lineTotalUsd:2}],payments:[],changeUsd:0,changeLbp:0,returns:[]};
beforeEach(()=>{document.cookie='XSRF-TOKEN=test; path=/'});afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe('financial and management workflows',()=>{
 it('submits manager credentials for a sale-bound approval',async()=>{const fetch=vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json({id:'approval-1'},{status:201}));const done=vi.fn();render(<ApprovalDialog saleId="sale-1" operation="DISCOUNT" reason="Large discount" done={done} close={()=>{}}/>);await userEvent.type(screen.getByLabelText('Manager username'),'manager');await userEvent.type(screen.getByLabelText('Manager password'),'very-secret');await userEvent.click(screen.getByRole('button',{name:'Approve action'}));await waitFor(()=>expect(done).toHaveBeenCalledWith('approval-1'));expect(String(fetch.mock.calls[0][0])).toContain('/api/pos/approvals');expect(fetch.mock.calls[0][1]?.body).toContain('managerUsername')});
 it('shows an approval dialog after backend rejects a teller discount',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify({message:'Valid manager approval required'}),{status:403,headers:{'Content-Type':'application/json'}}));render(<SaleActionDialog sale={{...sale,status:'OPEN'}} item={sale.items[0]} kind="line-discount" done={()=>{}} close={()=>{}}/>);await userEvent.type(screen.getByLabelText('Discount amount'),'1');await userEvent.type(screen.getByLabelText('Reason'),'Promotion');await userEvent.click(screen.getByRole('button',{name:'Apply'}));expect(await screen.findByRole('heading',{name:'Manager approval'})).toBeVisible()});
 it('captures price override value and reason',async()=>{const fetch=vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json({...sale,status:'OPEN'}));render(<SaleActionDialog sale={{...sale,status:'OPEN'}} item={sale.items[0]} kind="override" done={()=>{}} close={()=>{}}/>);await userEvent.type(screen.getByLabelText('Requested unit price'),'0.75');await userEvent.type(screen.getByLabelText('Reason'),'Damaged box');await userEvent.click(screen.getByRole('button',{name:'Apply'}));await waitFor(()=>expect(fetch).toHaveBeenCalled());expect(fetch.mock.calls[0][1]?.body).toContain('unitPriceUsd')});
 it('paginates sales history',async()=>{const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async input=>Response.json({content:[sale],page:String(input).includes('page=1')?1:0,size:20,totalElements:21,totalPages:2}));render(<AdvancedSales role="MANAGER"/>);expect(await screen.findByText('S-1')).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Next'}));await waitFor(()=>expect(fetch.mock.calls.some(c=>String(c[0]).includes('page=1'))).toBe(true))});
 it('records a return quantity, refund method, and restock choice',async()=>{const returned={...sale,returns:[{id:'r1',refundUsd:1,method:'USD_CASH',reason:'Wrong item',createdAt:'2026-09-21T11:00:00Z',items:[{saleItemId:'item-1',quantity:1,amountUsd:1,restockable:true}]}]};const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.includes('/returns')&&init?.method==='POST')return Response.json({id:'r1'},{status:201});if(url.includes('/sales/sale-1'))return Response.json(returned);return Response.json({content:[sale],page:0,size:20,totalElements:1,totalPages:1})});render(<AdvancedSales role="MANAGER"/>);await userEvent.click(await screen.findByText('S-1'));await userEvent.click(screen.getByRole('button',{name:'Return / refund'}));await userEvent.clear(screen.getByLabelText('Return quantity Mug'));await userEvent.type(screen.getByLabelText('Return quantity Mug'),'1');await userEvent.click(screen.getByText('Restockable'));await userEvent.type(screen.getByLabelText('Reason'),'Wrong item');await userEvent.click(screen.getByRole('button',{name:'Record return and refund'}));await waitFor(()=>expect(fetch.mock.calls.some(c=>String(c[0]).includes('/returns'))).toBe(true))});
 it('restocks inventory and reloads authoritative stock',async()=>{const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.includes('/movements'))return Response.json([]);if(init?.method==='POST')return Response.json({});return Response.json([{productId:'p1',sku:'P1',productName:'Mug',category:'Home',stock:2,lowStockThreshold:1,stockStatus:'IN_STOCK',inventoryValue:2}])});render(<AdvancedInventory/>);await userEvent.click(await screen.findByRole('button',{name:'Manage'}));await userEvent.type(screen.getByLabelText('Quantity received'),'4');await userEvent.type(screen.getByLabelText('Reason'),'Supplier delivery');await userEvent.click(screen.getByRole('button',{name:'Save movement'}));await waitFor(()=>expect(fetch.mock.calls.some(c=>String(c[0]).endsWith('/restock'))).toBe(true))});
 it('supports report presets and custom dates',async()=>{const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async input=>String(input).includes('/dashboard')?Response.json({netSales:0,completedTransactions:0,totalRefunds:0}):Response.json(String(input).includes('/payments')?{}:[]));render(<AdvancedReports/>);await screen.findByText('Net sales');await userEvent.click(screen.getByRole('button',{name:'Yesterday'}));fireEvent.change(screen.getByLabelText('Report from'),{target:{value:'2026-09-01'}});await waitFor(()=>expect(fetch.mock.calls.some(c=>String(c[0]).includes('from=2026-09-01'))).toBe(true))});
 it('creates employees without rendering their password',async()=>{const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(_input,init)=>init?.method==='POST'?Response.json({id:'e1'},{status:201}):Response.json([]));render(<AdvancedAdmin/>);await userEvent.click(await screen.findByRole('button',{name:'Create employee'}));await userEvent.type(screen.getByLabelText('Username'),'newteller');await userEvent.type(screen.getByLabelText('Display name'),'New Teller');await userEvent.type(screen.getByLabelText(/Initial password/),'a-strong-password-123');await userEvent.click(screen.getAllByRole('button',{name:'Create employee'}).at(-1)!);await waitFor(()=>expect(fetch.mock.calls.some(c=>c[1]?.method==='POST')).toBe(true));expect(screen.queryByText('a-strong-password-123')).not.toBeInTheDocument()});
});
