package com.chahinaz.pos;
import com.chahinaz.pos.catalogue.*;
import com.chahinaz.pos.employee.*;
import com.chahinaz.pos.settings.*;
import java.math.BigDecimal;
import java.util.UUID;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.junit.jupiter.*;
import org.testcontainers.postgresql.PostgreSQLContainer;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@Testcontainers @SpringBootTest(properties={"POS_BOOTSTRAP_ADMIN_USERNAME=bootstrap","POS_BOOTSTRAP_ADMIN_PASSWORD=development-test-password-only"}) @AutoConfigureMockMvc
class Phase3PostgresIntegrationTest {
 @Container static PostgreSQLContainer postgres=new PostgreSQLContainer("postgres:16-alpine");
 @DynamicPropertySource static void db(DynamicPropertyRegistry p){p.add("spring.datasource.url",postgres::getJdbcUrl);p.add("spring.datasource.username",postgres::getUsername);p.add("spring.datasource.password",postgres::getPassword);}
 @Autowired MockMvc mvc; @Autowired ProductRepository products; @Autowired CategoryRepository categories; @Autowired SettingRepository settings; @Autowired EmployeeRepository employees; @Autowired PasswordEncoder encoder; @Autowired JdbcTemplate jdbc;
 @BeforeEach void rate(){Employee a=employees.findByUsernameIgnoreCase("bootstrap").orElseThrow();settings.saveAndFlush(new StoreSetting("currency.usd_to_lbp","89500",a.id));}
 Product product(String price,int stock,boolean active){Category c=categories.saveAndFlush(new Category("C"+UUID.randomUUID(),null));Product p=new Product("S"+UUID.randomUUID(),c);p.name="Test product";p.description="Snapshot description";p.costPriceUsd=new BigDecimal("0.50");p.sellingPriceUsd=new BigDecimal(price);p.stockQuantity=stock;p.lowStockThreshold=1;p.active=active;return products.saveAndFlush(p);}
 String create(String who,String role)throws Exception{return mvc.perform(post("/api/pos/sales").with(user(who).roles(role)).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"note\":\"Counter sale\"}" )).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();}
 UUID id(String body){return UUID.fromString(body.replaceAll(".*\"id\":\"([^\"]+)\".*","$1"));}
 UUID itemId(String body){return UUID.fromString(body.replaceAll(".*\"items\":\\[\\{\"id\":\"([^\"]+)\".*","$1"));}
 String add(UUID sale,Product p,int q)throws Exception{return mvc.perform(post("/api/pos/sales/{id}/items",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"productId\":\""+p.id+"\",\"quantity\":"+q+"}" )).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();}
 @Test void openSaleSupportsAddIncreaseUpdateRemoveWithoutStockChange()throws Exception{Product p=product("2.50",5,true);UUID sale=id(create("bootstrap","ADMIN"));String b=add(sale,p,1);b=add(sale,p,2);assertTrue(b.contains("\"quantity\":3"));assertEquals(5,products.findById(p.id).orElseThrow().stockQuantity);UUID item=itemId(b);mvc.perform(put("/api/pos/sales/{s}/items/{i}",sale,item).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"quantity\":2}")).andExpect(status().isOk()).andExpect(jsonPath("$.totalUsd").value(5.0));mvc.perform(delete("/api/pos/sales/{s}/items/{i}",sale,item).with(user("bootstrap").roles("ADMIN")).with(csrf())).andExpect(status().isOk()).andExpect(jsonPath("$.items").isEmpty());assertEquals(5,products.findById(p.id).orElseThrow().stockQuantity);}
 @Test void completionDeductsStockSnapshotsPriceRateAndCreatesMovement()throws Exception{Product p=product("2.50",5,true);UUID sale=id(create("bootstrap","ADMIN"));add(sale,p,2);mvc.perform(post("/api/pos/sales/{id}/complete",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidUsd\":10,\"paidLbp\":0,\"whishUsd\":0,\"whishManuallyConfirmed\":false}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("COMPLETED")).andExpect(jsonPath("$.exchangeRate").value(89500.0)).andExpect(jsonPath("$.changeUsd").value(5.0)).andExpect(jsonPath("$.changeLbp").value(0));assertEquals(3,products.findById(p.id).orElseThrow().stockQuantity);assertEquals(1,jdbc.queryForObject("select count(*) from inventory_movement where sale_id=? and movement_type='SALE'",Integer.class,sale));p.name="Changed";p.sellingPriceUsd=new BigDecimal("9.00");products.saveAndFlush(p);settings.findById("currency.usd_to_lbp").ifPresent(x->{x.value="100000";settings.saveAndFlush(x);});mvc.perform(get("/api/pos/sales/{id}",sale).with(user("bootstrap").roles("ADMIN"))).andExpect(jsonPath("$.items[0].name").value("Test product")).andExpect(jsonPath("$.items[0].unitPriceUsd").value(2.5)).andExpect(jsonPath("$.exchangeRate").value(89500.0));mvc.perform(post("/api/pos/sales/{id}/items",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"productId\":\""+p.id+"\",\"quantity\":1}")).andExpect(status().isConflict());}
 @Test void lbpMixedWhishAndDeterministicChangeWork()throws Exception{Product p=product("10.00",10,true);UUID lbpSale=id(create("bootstrap","ADMIN"));add(lbpSale,p,1);mvc.perform(post("/api/pos/sales/{id}/complete",lbpSale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidLbp\":895000}" )).andExpect(status().isOk()).andExpect(jsonPath("$.changeUsd").value(0.0));UUID mixed=id(create("bootstrap","ADMIN"));add(mixed,p,1);mvc.perform(post("/api/pos/sales/{id}/complete",mixed).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidUsd\":5,\"paidLbp\":452500}" )).andExpect(status().isOk()).andExpect(jsonPath("$.changeUsd").value(0.0)).andExpect(jsonPath("$.changeLbp").value(5000));UUID whish=id(create("bootstrap","ADMIN"));add(whish,p,1);mvc.perform(post("/api/pos/sales/{id}/complete",whish).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"whishUsd\":10,\"whishManuallyConfirmed\":false}" )).andExpect(status().isBadRequest());mvc.perform(post("/api/pos/sales/{id}/complete",whish).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"whishUsd\":10,\"whishManuallyConfirmed\":true}" )).andExpect(status().isOk()).andExpect(jsonPath("$.payments[0].type").value("WHISH_MANUAL"));}
 @Test void invalidEmptyInactiveInsufficientAndRollbackAreRejected()throws Exception{UUID empty=id(create("bootstrap","ADMIN"));mvc.perform(post("/api/pos/sales/{id}/complete",empty).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidUsd\":1}" )).andExpect(status().isConflict());Product inactive=product("1.00",1,false);UUID s=id(create("bootstrap","ADMIN"));mvc.perform(post("/api/pos/sales/{id}/items",s).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"productId\":\""+inactive.id+"\",\"quantity\":1}")).andExpect(status().isConflict());Product p=product("3.00",1,true);add(s,p,2);mvc.perform(post("/api/pos/sales/{id}/complete",s).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidUsd\":6}" )).andExpect(status().isConflict());assertEquals(1,products.findById(p.id).orElseThrow().stockQuantity);assertEquals(0,jdbc.queryForObject("select count(*) from inventory_movement where sale_id=?",Integer.class,s));Product q=product("3.00",5,true);UUID shortPay=id(create("bootstrap","ADMIN"));add(shortPay,q,1);mvc.perform(post("/api/pos/sales/{id}/complete",shortPay).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidUsd\":2}" )).andExpect(status().isConflict());assertEquals(5,products.findById(q.id).orElseThrow().stockQuantity);}
 @Test void authenticationOwnershipHistoryAndCsrfRemainEnforced()throws Exception{String teller="t"+UUID.randomUUID();employees.saveAndFlush(new Employee(teller,"Teller",encoder.encode("long-development-password"),Role.TELLER));UUID sale=id(create(teller,"TELLER"));mvc.perform(get("/api/pos/sales/{id}",sale)).andExpect(status().is3xxRedirection());mvc.perform(post("/api/pos/sales").with(user(teller).roles("TELLER")).contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isForbidden());mvc.perform(get("/api/pos/sales/{id}",sale).with(user("other").roles("TELLER"))).andExpect(status().isForbidden());mvc.perform(get("/api/pos/sales").with(user(teller).roles("TELLER"))).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].id").value(sale.toString()));mvc.perform(get("/api/pos/sales").with(user("bootstrap").roles("ADMIN"))).andExpect(status().isOk());assertEquals(1,jdbc.queryForObject("select count(*) from audit_event where action='SALE_CREATED' and entity_id=?",Integer.class,sale.toString()));}
}
