package com.chahinaz.pos;

import com.chahinaz.pos.catalogue.*;
import com.chahinaz.pos.employee.*;
import com.chahinaz.pos.settings.*;
import java.math.BigDecimal;
import java.util.UUID;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.*;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.junit.jupiter.*;
import org.testcontainers.postgresql.PostgreSQLContainer;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@Testcontainers @SpringBootTest(properties={"POS_BOOTSTRAP_ADMIN_USERNAME=bootstrap","POS_BOOTSTRAP_ADMIN_PASSWORD=development-test-password-only"}) @AutoConfigureMockMvc
class Phase4PostgresIntegrationTest {
 @Container static PostgreSQLContainer postgres=new PostgreSQLContainer("postgres:16-alpine");
 @DynamicPropertySource static void db(DynamicPropertyRegistry p){p.add("spring.datasource.url",postgres::getJdbcUrl);p.add("spring.datasource.username",postgres::getUsername);p.add("spring.datasource.password",postgres::getPassword);}
 @Autowired MockMvc mvc;@Autowired ProductRepository products;@Autowired CategoryRepository categories;@Autowired EmployeeRepository employees;@Autowired SettingRepository settings;@Autowired PasswordEncoder encoder;@Autowired JdbcTemplate jdbc;
 @BeforeEach void config(){Employee a=employees.findByUsernameIgnoreCase("bootstrap").orElseThrow();settings.saveAndFlush(new StoreSetting("currency.usd_to_lbp","89500",a.id));settings.saveAndFlush(new StoreSetting("pos.teller_discount_max_percent","5",a.id));}
 Employee employee(Role role){String name=role.name().toLowerCase()+UUID.randomUUID();return employees.saveAndFlush(new Employee(name,role.name()+" User",encoder.encode("long-development-password"),role));}
 Product product(int stock){Category c=categories.saveAndFlush(new Category("C"+UUID.randomUUID(),null));Product p=new Product("S"+UUID.randomUUID(),c);p.name="Phase 4 item";p.costPriceUsd=new BigDecimal("1.00");p.sellingPriceUsd=new BigDecimal("10.00");p.stockQuantity=stock;p.lowStockThreshold=1;return products.saveAndFlush(p);}
 String create(String user,String role)throws Exception{return mvc.perform(post("/api/pos/sales").with(user(user).roles(role)).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();}
 UUID id(String json){return UUID.fromString(json.replaceAll(".*\"id\":\"([^\"]+)\".*","$1"));}
 UUID itemId(String json){return UUID.fromString(json.replaceAll(".*\"items\":\\[\\{\"id\":\"([^\"]+)\".*","$1"));}
 String add(UUID sale,Product p,String user,String role)throws Exception{return mvc.perform(post("/api/pos/sales/{id}/items",sale).with(user(user).roles(role)).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"productId\":\""+p.id+"\",\"quantity\":1}" )).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();}
 UUID openRegister(String user,String role,String usd,String lbp)throws Exception{String json=mvc.perform(post("/api/pos/registers/open").with(user(user).roles(role)).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"openingCashUsd\":"+usd+",\"openingCashLbp\":"+lbp+"}" )).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return id(json);}
 void complete(UUID sale,String user,String role)throws Exception{mvc.perform(post("/api/pos/sales/{id}/complete",sale).with(user(user).roles(role)).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidUsd\":10}" )).andExpect(status().isOk());}

 @Test void registerOpenDuplicateCloseAndDifferenceAreAudited()throws Exception{Employee teller=employee(Role.TELLER),other=employee(Role.TELLER);UUID register=openRegister(teller.username,"TELLER","100.00","50000");mvc.perform(post("/api/pos/registers/open").with(user(teller.username).roles("TELLER")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"openingCashUsd\":0,\"openingCashLbp\":0}" )).andExpect(status().isConflict());mvc.perform(post("/api/pos/registers/{id}/close",register).with(user(other.username).roles("TELLER")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"actualCashUsd\":100,\"actualCashLbp\":50000}" )).andExpect(status().isForbidden());mvc.perform(post("/api/pos/registers/{id}/close",register).with(user(teller.username).roles("TELLER")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"actualCashUsd\":98.00,\"actualCashLbp\":55000,\"note\":\"Counted twice\"}" )).andExpect(status().isOk()).andExpect(jsonPath("$.expectedCashUsd").value(100.0)).andExpect(jsonPath("$.differenceUsd").value(-2.0)).andExpect(jsonPath("$.differenceLbp").value(5000));assertEquals(2,jdbc.queryForObject("select count(*) from audit_event where entity_id=? and action like 'REGISTER_%'",Integer.class,register.toString()));}

 @Test void heldResumeAndVoidPreserveInventoryAndRejectInvalidTransitions()throws Exception{Product p=product(3);UUID sale=id(create("bootstrap","ADMIN"));add(sale,p,"bootstrap","ADMIN");mvc.perform(post("/api/pos/sales/{id}/hold",sale).with(user("bootstrap").roles("ADMIN")).with(csrf())).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("HELD"));assertEquals(3,products.findById(p.id).orElseThrow().stockQuantity);mvc.perform(post("/api/pos/sales/{id}/resume",sale).with(user("bootstrap").roles("ADMIN")).with(csrf())).andExpect(status().isOk());mvc.perform(post("/api/pos/sales/{id}/void",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"Customer cancelled\"}" )).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("VOIDED"));assertEquals(3,products.findById(p.id).orElseThrow().stockQuantity);mvc.perform(post("/api/pos/sales/{id}/resume",sale).with(user("bootstrap").roles("ADMIN")).with(csrf())).andExpect(status().isConflict());}

 @Test void tellerCashCompletionNeedsRegisterAndOwnershipStillApplies()throws Exception{Employee teller=employee(Role.TELLER);Product p=product(2);UUID sale=id(create(teller.username,"TELLER"));add(sale,p,teller.username,"TELLER");mvc.perform(post("/api/pos/sales/{id}/complete",sale).with(user(teller.username).roles("TELLER")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidUsd\":10}" )).andExpect(status().isConflict());openRegister(teller.username,"TELLER","0","0");complete(sale,teller.username,"TELLER");mvc.perform(get("/api/pos/sales/{id}",sale).with(user("someone-else").roles("TELLER"))).andExpect(status().isForbidden());mvc.perform(post("/api/pos/sales/{id}/void",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"No destructive void\"}" )).andExpect(status().isConflict());}

 @Test void discountAndPriceOverrideRequireRealApprovalAndRetainOriginalPrice()throws Exception{Employee teller=employee(Role.TELLER),manager=employee(Role.MANAGER);Product p=product(5);UUID sale=id(create(teller.username,"TELLER"));String added=add(sale,p,teller.username,"TELLER");UUID item=itemId(added);mvc.perform(post("/api/pos/sales/{s}/discount",sale).with(user(teller.username).roles("TELLER")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"amountUsd\":2,\"reason\":\"Promotion\"}" )).andExpect(status().isForbidden());String approval=mvc.perform(post("/api/management/approvals").with(user(manager.username).roles("MANAGER")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"operationType\":\"PRICE_OVERRIDE\",\"requestingUsername\":\""+teller.username+"\",\"targetType\":\"sale\",\"targetId\":\""+sale+"\",\"reason\":\"Damaged package\"}" )).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();UUID approvalId=id(approval);mvc.perform(post("/api/pos/sales/{s}/items/{i}/price-override",sale,item).with(user(teller.username).roles("TELLER")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"unitPriceUsd\":7.50,\"reason\":\"Damaged package\",\"approvalId\":\""+approvalId+"\"}" )).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].originalUnitPriceUsd").value(10.0)).andExpect(jsonPath("$.items[0].unitPriceUsd").value(7.5));mvc.perform(post("/api/pos/sales/{s}/items/{i}/price-override",sale,item).with(user(teller.username).roles("TELLER")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"unitPriceUsd\":6,\"reason\":\"Reuse fake approval\",\"approvalId\":\""+approvalId+"\"}" )).andExpect(status().isForbidden());}

 @Test void discountsAreDeterministicAndCannotMakeSaleNegative()throws Exception{Product p=product(2);UUID sale=id(create("bootstrap","ADMIN"));UUID item=itemId(add(sale,p,"bootstrap","ADMIN"));mvc.perform(post("/api/pos/sales/{s}/items/{i}/discount",sale,item).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"amountUsd\":2,\"reason\":\"Store promotion\"}" )).andExpect(status().isOk()).andExpect(jsonPath("$.subtotalUsd").value(10.0)).andExpect(jsonPath("$.totalDiscountUsd").value(2.0)).andExpect(jsonPath("$.totalUsd").value(8.0));mvc.perform(post("/api/pos/sales/{s}/discount",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"amountUsd\":3,\"reason\":\"Manager promotion\"}" )).andExpect(status().isOk()).andExpect(jsonPath("$.totalDiscountUsd").value(5.0)).andExpect(jsonPath("$.totalUsd").value(5.0));mvc.perform(post("/api/pos/sales/{s}/discount",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"amountUsd\":9,\"reason\":\"Invalid promotion\"}" )).andExpect(status().isBadRequest());}

 @Test void partialReturnsUseSaleSnapshotAndRestockOnlyWhenRequested()throws Exception{Product p=product(5);UUID sale=id(create("bootstrap","ADMIN"));String added=mvc.perform(post("/api/pos/sales/{id}/items",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"productId\":\""+p.id+"\",\"quantity\":3}" )).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();UUID item=itemId(added);mvc.perform(post("/api/pos/sales/{id}/complete",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"paidUsd\":30}" )).andExpect(status().isOk());assertEquals(2,products.findById(p.id).orElseThrow().stockQuantity);openRegister("bootstrap","ADMIN","100","0");mvc.perform(post("/api/management/sales/{id}/returns",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"items\":[{\"saleItemId\":\""+item+"\",\"quantity\":1,\"restockable\":true}],\"refundMethod\":\"USD_CASH\",\"reason\":\"Customer return\"}" )).andExpect(status().isCreated()).andExpect(jsonPath("$.refundUsd").value(10.0));assertEquals(3,products.findById(p.id).orElseThrow().stockQuantity);Product repriced=products.findById(p.id).orElseThrow();repriced.sellingPriceUsd=new BigDecimal("99.00");products.saveAndFlush(repriced);mvc.perform(post("/api/management/sales/{id}/returns",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"items\":[{\"saleItemId\":\""+item+"\",\"quantity\":1,\"restockable\":false}],\"refundMethod\":\"USD_CASH\",\"reason\":\"Damaged return\"}" )).andExpect(status().isCreated()).andExpect(jsonPath("$.refundUsd").value(10.0));assertEquals(3,products.findById(p.id).orElseThrow().stockQuantity);mvc.perform(post("/api/management/sales/{id}/returns",sale).with(user("bootstrap").roles("ADMIN")).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"items\":[{\"saleItemId\":\""+item+"\",\"quantity\":2,\"restockable\":false}],\"refundMethod\":\"USD_CASH\",\"reason\":\"Excess return\"}" )).andExpect(status().isConflict());assertEquals(2,jdbc.queryForObject("select count(*) from sale_return where original_sale_id=?",Integer.class,sale));assertEquals(1,jdbc.queryForObject("select count(*) from inventory_movement where return_id is not null and movement_type='RETURN'",Integer.class));}
}

