package com.chahinaz.pos.operations;
import com.chahinaz.pos.audit.AuditService;import com.chahinaz.pos.employee.*;import static com.chahinaz.pos.operations.RegisterDtos.*;
import java.math.*;import java.time.Instant;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.Authentication;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
@Service public class RegisterService {
 private final RegisterSessionRepository registers;private final EmployeeRepository employees;private final AuditService audit;private final JdbcTemplate jdbc;
 public RegisterService(RegisterSessionRepository r,EmployeeRepository e,AuditService a,JdbcTemplate j){registers=r;employees=e;audit=a;jdbc=j;}
 private Employee actor(Authentication a){return employees.findByUsernameIgnoreCase(a.getName()).orElseThrow();}
 private boolean elevated(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN")||x.getAuthority().equals("ROLE_MANAGER"));}
 @Transactional public View open(OpenInput in,Authentication auth){Employee e=actor(auth);if(registers.findByEmployeeIdAndStatus(e.getId(),RegisterStatus.OPEN).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Employee already has an open register");RegisterSession r=registers.saveAndFlush(new RegisterSession(e,in.openingCashUsd().setScale(2),in.openingCashLbp().setScale(0)));audit.record(e.getId(),"REGISTER_OPENED","register_session",r.id.toString(),null,"USD="+r.openingCashUsd+"; LBP="+r.openingCashLbp);return view(r);}
 @Transactional public View close(UUID id,CloseInput in,Authentication auth){Employee e=actor(auth);RegisterSession r=registers.findLocked(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Register not found"));if(r.status!=RegisterStatus.OPEN)throw new ResponseStatusException(HttpStatus.CONFLICT,"Register is already closed");if(!elevated(auth)&&!r.employee.getId().equals(e.getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Register belongs to another employee");BigDecimal salesUsd=sum("select coalesce(sum(amount_paid_usd-change_usd),0) from sale where register_session_id=? and status='COMPLETED'",id,2);BigDecimal salesLbp=sum("select coalesce(sum(amount_paid_lbp-change_lbp),0) from sale where register_session_id=? and status='COMPLETED'",id,0);BigDecimal refundsUsd=sum("select coalesce(sum(refund_usd),0) from sale_return where register_session_id=? and refund_method='USD_CASH'",id,2);BigDecimal refundsLbp=sum("select coalesce(sum(refund_lbp),0) from sale_return where register_session_id=? and refund_method='LBP_CASH'",id,0);r.expectedClosingCashUsd=r.openingCashUsd.add(salesUsd).subtract(refundsUsd);r.expectedClosingCashLbp=r.openingCashLbp.add(salesLbp).subtract(refundsLbp);r.actualClosingCashUsd=in.actualCashUsd().setScale(2);r.actualClosingCashLbp=in.actualCashLbp().setScale(0);r.differenceUsd=r.actualClosingCashUsd.subtract(r.expectedClosingCashUsd);r.differenceLbp=r.actualClosingCashLbp.subtract(r.expectedClosingCashLbp);r.closingNote=blank(in.note());r.closedAt=Instant.now();r.status=RegisterStatus.CLOSED;registers.saveAndFlush(r);audit.record(e.getId(),"REGISTER_CLOSED","register_session",id.toString(),null,"USD difference="+r.differenceUsd+"; LBP difference="+r.differenceLbp);return view(r);}
 @Transactional(readOnly=true) public View current(Authentication a){Employee e=actor(a);return registers.findByEmployeeIdAndStatus(e.getId(),RegisterStatus.OPEN).map(this::view).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"No open register"));}
 @Transactional(readOnly=true) public List<View> history(Authentication a){Employee e=actor(a);return registers.findByEmployeeIdOrderByOpenedAtDesc(e.getId()).stream().map(this::view).toList();}
 @Transactional(readOnly=true) public RegisterSession requireOpen(Employee e){return registers.findByEmployeeIdAndStatus(e.getId(),RegisterStatus.OPEN).orElseThrow(()->new ResponseStatusException(HttpStatus.CONFLICT,"Open a register before completing a cash operation"));}
 @Transactional(readOnly=true) public Optional<RegisterSession> openFor(Employee e){return registers.findByEmployeeIdAndStatus(e.getId(),RegisterStatus.OPEN);}
 private BigDecimal sum(String sql,UUID id,int scale){return jdbc.queryForObject(sql,BigDecimal.class,id).setScale(scale);}
 private View view(RegisterSession r){return new View(r.id,r.employee.getId(),r.employee.getDisplayName(),r.status,r.openedAt,r.closedAt,r.openingCashUsd,r.openingCashLbp,r.expectedClosingCashUsd,r.expectedClosingCashLbp,r.actualClosingCashUsd,r.actualClosingCashLbp,r.differenceUsd,r.differenceLbp,r.closingNote);}
 private static String blank(String x){return x==null||x.isBlank()?null:x.trim();}
}
